[mypy]
strict = True
show_error_codes = True
disallow_any_explicit = True
disallow_any_unimported = True
enable_error_code = comparison-overlap,deprecated,explicit-any,explicit-override,exhaustive-match,ignore-without-code,mutable-override,no-any-return,no-any-unimported,no-untyped-call,no-untyped-def,possibly-undefined,redundant-cast,redundant-expr,redundant-self,truthy-bool,truthy-iterable,type-arg,unimported-reveal,unreachable,unused-awaitable,unused-ignore,untyped-decorator
files = cytoolz/*.pyi, cytoolz/curried/*.pyi
