package:
    name: cytoolz
    version: "0.11.0"

build:
    number: {{environ.get('BINSTAR_BUILD', 1)}}

requirements:
    build:
      - setuptools
      - python
      - cython
      - toolz
      - libpython # [win and not (win64 and py34)]

    run:
      - python
      - libpython # [win and not (win64 and py34)]

test:
    requires:
      - pytest
      - toolz
    imports:
      - cytoolz
    commands:
      - py.test -x --doctest-modules --pyargs cytoolz

about:
    home: https://toolz.readthedocs.io/
    license: BSD
