name: Test

on:
  push:
    branches:
      - master
      - release
  pull_request:

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest", "macos-latest", "windows-latest"]
        cython-version: ["0.29.37", "3.1.4"]
        python-version:
          - "3.9"
          - "3.10"
          - "3.11"
          - "3.12"
          - "3.13"
          - "3.14"
          - "pypy3.9"
          - "pypy3.10"
          - "pypy3.11"
        exclude:
          - cython-version: "0.29.37"
            python-version: "3.13"
          - cython-version: "0.29.37"
            python-version: "3.14"
          - cython-version: "0.29.37"
            python-version: "pypy3.11"
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel
          pip install cython==${{ matrix.cython-version }} pytest
          pip install git+https://github.com/pytoolz/toolz.git
          python setup.py build_ext --inplace --with-cython
          pip install -e .
      - name: PyTest
        run: |
          pytest --doctest-modules cytoolz/
          # For convenience, make sure simple test commands work
          pytest
          # Make sure we can cimport cytoolz
          echo 'cimport cytoolz ; from cytoolz.functoolz cimport memoize' > try_cimport_cytoolz.pyx
          cythonize -i try_cimport_cytoolz.pyx
          python -c 'import try_cimport_cytoolz'
