name: Build wheels

on:
  pull_request:  # Uncomment to debug wheel building in a PR
  push:
    branches:
      - master
    tags:
      - '[0-9]+.[0-9]+.[0-9]+*'

jobs:
  wheels:
    name: Build wheels for ${{ matrix.os }}
    runs-on: ${{ matrix.runs-on }}
    defaults:
      run:
        shell: bash -l {0}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: linux-intel
            runs-on: ubuntu-latest
            archs: auto64 auto32
          - os: linux-arm
            runs-on: ubuntu-24.04-arm
            archs: auto64 auto32
          - os: linux-qemu-ppc64le
            runs-on: ubuntu-latest
            archs: ppc64le
          - os: linux-qemu-s390x
            runs-on: ubuntu-latest
            archs: s390x
          - os: linux-qemu-riscv64
            runs-on: ubuntu-latest
            archs: riscv64
          - os: windows-intel
            runs-on: windows-latest
            archs: auto64 auto32
          - os: windows-arm
            runs-on: windows-11-arm
            archs: auto64 auto32
          - os: macos-intel
            # macos-15-intel is the last x86_64 runner
            runs-on: macos-15-intel
            archs: auto
          - os: macos-arm
            # macos-14+ (including latest) are ARM64 runners
            runs-on: macos-latest
            archs: auto universal2
          - os: ios
            runs-on: macos-latest
            platform: ios
            archs: all
          - os: pyodide
            runs-on: ubuntu-latest
            platform: pyodide
            archs: all

    steps:
      - name: Setup QEMU
        if: ${{ startsWith(matrix.os, 'linux-qemu') }}
        uses: docker/setup-qemu-action@v3
        with:
          platforms: all
      - name: Checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
          persist-credentials: false
      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.x"
      - name: Build wheels
        uses: pypa/cibuildwheel@v3.2.1
        env:
          CIBW_PLATFORM: ${{ matrix.platform || 'auto' }}
          CIBW_ARCHS: ${{ matrix.archs || 'auto' }}
          CIBW_BUILD: "cp* pp*"
          CIBW_ENABLE: "cpython-freethreading pypy"
          CIBW_TEST_SKIP: "*-ios_*"
      - name: List wheels
        run: |
          ls -al wheelhouse/
      - name: Upload wheels
        uses: actions/upload-artifact@v4
        with:
          name: cibw-wheels-${{ matrix.os }}-${{ strategy.job-index }}
          path: ./wheelhouse/*.whl
          retention-days: 7

  sdist:
    name: Build source distribution
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
          persist-credentials: false
      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.9"
      - name: Install build dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install build
      - name: Build sdist
        run: python -m build --sdist
      - name: Upload sdist
        uses: actions/upload-artifact@v4
        with:
          name: cibw-sdist
          path: dist/*.tar.gz
          retention-days: 7

  upload_all:
    needs: [wheels, sdist]
    runs-on: ubuntu-latest
    steps:
      - name: Download dist artifacts
        uses: actions/download-artifact@v5
        with:
          pattern: cibw-*
          path: dist
          merge-multiple: true
      - name: List artifacts
        run: |
          ls -al dist/
      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@v1.13.0
        if: startsWith(github.ref, 'refs/tags/') && github.repository == 'pytoolz/cytoolz'
        with:
          user: __token__
          password: ${{ secrets.PYPI_TOKEN }}
